<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GG0PK5N" failures="1" tests="5" name="testcases.LoginSauce" time="7.711" errors="0" timestamp="2024-07-31T18:02:26 EEST" skipped="0">
  <testcase classname="testcases.LoginSauce" name="loginTest" time="2.314">
    <failure message="Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login attempt with username: locked_out_user and password: secret_sauce failed. expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testcases.LoginSauce.loginTest(LoginSauce.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
    <system-out>
      <![CDATA[Method name is loginTest
Status of execution is -> 2
<a href="C:\Users\motzos\Desktop\JavaTesting\automationtesting\screenshot\Wed.Jul.31.18-02-16.EEST.2024.png">Failure screeshot</a>]]>
    </system-out>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="1.380">
    <system-out>
      <![CDATA[Method name is loginTest
Status of execution is -> 1]]>
    </system-out>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="1.382">
    <system-out>
      <![CDATA[Method name is loginTest
Status of execution is -> 1]]>
    </system-out>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="1.251">
    <system-out>
      <![CDATA[Method name is loginTest
Status of execution is -> 1]]>
    </system-out>
  </testcase> <!-- loginTest -->
  <testcase classname="testcases.LoginSauce" name="loginTest" time="1.384">
    <system-out>
      <![CDATA[Method name is loginTest
Status of execution is -> 1]]>
    </system-out>
  </testcase> <!-- loginTest -->
  <system-out>
    <![CDATA[Method name is loginTest
Status of execution is -> 1
Method name is loginTest
Status of execution is -> 1
Method name is loginTest
Status of execution is -> 2
<a href="C:\Users\motzos\Desktop\JavaTesting\automationtesting\screenshot\Wed.Jul.31.18-02-16.EEST.2024.png">Failure screeshot</a>
Method name is loginTest
Status of execution is -> 1
Method name is loginTest
Status of execution is -> 1
Method name is checkItems
Status of execution is -> 1
Method name is checkCart
Status of execution is -> 1
Method name is checkRemoveButton
Status of execution is -> 1
Method name is itemSorting
Status of execution is -> 1]]>
  </system-out>
</testsuite> <!-- testcases.LoginSauce -->
